key = "steam"
name = "Steam Scanner / Store"

[[settings]]
name = "Steam API key"
key = "apiKey"
hint = "Obtain from [Steam API Dev page](https://steamcommunity.com/dev/apikey)"

[[settings]]
name = "SteamID"
key = "steamId"
hint = "In decimal format. Obtain from [an online tool](https://www.steamidfinder.com)"
