
name: Publish release

on:
  release:
    types: [published]

permissions: write-all
env:
  DOTNET_VERSION: '6.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Build'
      shell: bash
      run: |
          dotnet build --configuration Release
          mkdir -p release
          cp */bin/Release/net8.0/Gami.*.dll release
          zip -r -9 release release/*

    - name: Upload DLLs to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.zip
        asset_name: windows.zip
        tag: ${{ github.ref }}
        overwrite: true
        